### PR TITLE
Integration of thanos together with minio S3 buckets

### PR DESCRIPTION
**Pull request by pburgisser**

### CODE REVIEW

**Comment by pburgisser** [comment]
@mcanevet second time it times out, not sure where the issue is. As I told you, sometimes keycloak doesn't start correctly and some application like alertmanager keeps crashing as it gets a 404 where testing the OIDC. I'm already working on the manual deployment of keycloak operator on another branch.

**Comment by mcanevet** [comment]
I guess we can merge as one of the upgrade pipeline works, just the from scratch times out

**Review by mcanevet — APPROVED** [review]

**Pull request merged**
