### PR TITLE
Scrape metrics of argocd

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Review by mcanevet — CHANGES_REQUESTED** [review]
serviceMonitors are already enable in common values.yaml (https://github.com/camptocamp/camptocamp-devops-stack/blob/master/argocd/argocd/values.yaml) except for dex (I missed that one). The only thing you have to do is enable the metrics (it can't be done on the common values.yaml because it's used for the bootstrapping and as the prometheus operator is not deployed yet, we can't deploy the metrics during bootstrap). Could you please also enable dex metrics in other distribs?

**Comment by raphink** [comment]
As it stands today, it seems common values are totally ignored and replaced by the values passed by Terraform's `helm_release` instead.

When I look at any chart deployed with ArgoCD, none of them inherits the default values.

**Comment by mcanevet** [comment]
Well this is weird. It does not do deep merging, but it should at least append values... I'll have to take a look at this.

**Comment by mcanevet** [comment]
Fixed by #231

**Pull request closed without merging**
