### PR TITLE
Fix nat gateway discovery

### PR DESCRIPTION
**Pull request by ckaenzig**
NAT gateways on a public subnet doesn't make sense.

### CODE REVIEW

**Comment by mcanevet** [comment]
Indeed. This is weird it looks like it works anyway...
Could you please fork this repository to do some PR to avoid having a lot of dangling branches on upstream in the long term?

**Comment by mcanevet** [comment]
I'm very surprised that it does not work like this anyway for you as Terraform would have issue an error if the datasource filter didn't match any resources...
What makes you think that this is required? Do you have any error message from Terraform?

**Comment by ckaenzig** [comment]
I'm very surprised that it would work without this fix. I'm getting this error :
```
Error: no matching NAT gateway found: {
  Filter: [{
      Name: "state",
      Values: ["available"]
    },{
      Name: "subnet-id",
      Values: ["subnet-0941b2c3180be7065"]
    }]
}
```
It's quite obvious that it couldn't find any nat gateway associated with a public subnet.

**Comment by mcanevet** [comment]
We have to clarify this before merging this PR because it work in under other circumstances...

**Comment by mcanevet** [comment]
@ckaenzig it looks like the official module declares NAT gateways in public subnets : https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/af51566b67b83bf4ae949db82831eea090115e53/main.tf#L951-L954
I guess this is a standard way to do it, but it is definitely the reason why it works in my case but not yours.

**Comment by ckaenzig** [comment]
Ok, I checked that AWS documentation in detail and it turns out I didn't understand things correctly (things are clearer in the morning). Of course the NAT gateway will be used in route tables of private subnets, but the subnet given at the gateway creation must actually be a public one. So I'm closing this PR. Sorry for the noise.

**Pull request closed without merging**
